"""
Cluster labels for route recommendations.

Generated by: 2).Manual_Cluster_Labeling.ipynb
"""

CLUSTER_LABELS = {
    0: "Short and flat",
    1: "Very long alpine mixed",
    2: "Very short and flat",
    3: "Mixed surface multi-day tours",
    4: "Mid-length rolling hills",
    5: "Very Short Flat Mixed",
    6: "Long alpine mixed",
    7: "Very long rolling hills",
    8: "Very short flat mixed",
    9: "Exceptionally long alpine steep",
}
